correct naming

diff --git a/.github/workflows/deploy-service.yml b/.github/workflows/deploy-service.yml
--- a/.github/workflows/deploy-service.yml
+++ b/.github/workflows/deploy-service.yml
@@ -67,12 +67,12 @@ jobs:
         TASK_DEFINITION_ARN=$(aws ecs describe-task-definition --task-definition feature --query 'taskDefinition.taskDefinitionArn' --output text)
 
         # Check if the service already exists
-        SERVICE_EXISTS=$(aws ecs describe-services --cluster feature-cluster --services $SERVICE_NAME --query 'services[0].status' --output text || echo "MISSING")
+        SERVICE_EXISTS=$(aws ecs describe-services --cluster feature --services $SERVICE_NAME --query 'services[0].status' --output text || echo "MISSING")
 
         if [ "$SERVICE_EXISTS" == "MISSING" ]; then
           echo "Creating ECS service $SERVICE_NAME"
           aws ecs create-service \
-            --cluster feature-cluster \
+            --cluster feature \
             --service-name $SERVICE_NAME \
             --task-definition $TASK_DEFINITION_ARN \
             --desired-count 1 \
@@ -81,7 +81,7 @@ jobs:
         else
           echo "Updating ECS service $SERVICE_NAME"
           aws ecs update-service \
-            --cluster feature-cluster \
+            --cluster feature \
             --service $SERVICE_NAME \
             --task-definition $TASK_DEFINITION_ARN \
             --desired-count 1
